name = "ak-website"
main = "index.js"
compatibility_date = "2025-02-14"
keep_vars = true

vars = { AEM_ORG = "ynakagawa", AEM_SITE = "avantor-da" }

[env.dev]
vars = { AEM_ORG = "ynakagawa", AEM_SITE = "avantor-da" }
